name: CI
on:
  workflow_dispatch:
  pull_request:
    branches: [master]
  push:
    branches: [master]
jobs:
  build-test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v2.3.4
        with:
          path: kansei

      - name: Setup workspace
        uses: ichiro-its/ros2-ws-action/setup@v1.0.0
        with:
          distro: iron

      - name: Build workspace
        uses: ichiro-its/ros2-ws-action/build@v1.0.0

      - name: Test workspace
        uses: ichiro-its/ros2-ws-action/test@v1.0.0
